#!/usr/bin/env bash
# One-time (idempotent) secret hardening for this machine:
#   data/env-key + data/jwt-secret (plaintext, 0600)
#     → dotenvx-encrypted .env.secrets (repo root)
#     → private key stored only in the macOS Keychain (service: arcturus-dotenvx)
# Existing values are migrated as-is, so encrypted DB rows and live sessions survive.
#   bun run secrets:init
set -euo pipefail
cd "$(dirname "$0")/.."

# --input: prompt for each fresh value instead of auto-generating (used by
# server-up.sh's "직접 입력" menu choice). Blank input falls back to auto-generate.
INPUT_MODE=false
for arg in "$@"; do
  [ "$arg" = "--input" ] && INPUT_MODE=true
done

KEYCHAIN_SERVICE="arcturus-dotenvx"
SECRETS_FILE=".env.secrets"
DATA_DIR="${ARCTURUS_DATA_DIR:-apps/api/data}"

say()  { printf '\033[1;33m→ %s\033[0m\n' "$1"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$1"; }
warn() { printf '\033[1;31m! %s\033[0m\n' "$1"; }

if [ "$(uname)" != "Darwin" ]; then
  warn "이 스크립트는 macOS 전용입니다 (private key를 Keychain에 보관)."
  echo "  Linux에서는 ARCTURUS_ENV_KEY / ARCTURUS_JWT_SECRET 환경 변수를 직접 주입하거나"
  echo "  기본 파일 fallback(data/env-key·jwt-secret, 0600)을 그대로 사용하세요."
  exit 1
fi

# Prints the decrypted value of $1 using private key $2; empty when undecryptable.
# (`dotenvx get` exits 0 and echoes the ciphertext on key mismatch, so we
# compare values instead of trusting exit codes.)
decrypted() {
  local out
  out="$(DOTENV_PRIVATE_KEY_SECRETS="$2" bunx dotenvx get "$1" -f "$SECRETS_FILE" 2>/dev/null || true)"
  case "$out" in encrypted:* | '') echo '' ;; *) printf '%s' "$out" ;; esac
}

keys_file_pk() {
  [ -f .env.keys ] || { echo ''; return; }
  grep '^DOTENV_PRIVATE_KEY_SECRETS=' .env.keys | cut -d= -f2- | tr -d '"' || true
}

# 1. Locate an existing private key: keychain first, then a leftover .env.keys
#    (e.g. an interrupted earlier run).
PK="$(security find-generic-password -s "$KEYCHAIN_SERVICE" -w 2>/dev/null || true)"
[ -n "$PK" ] || PK="$(keys_file_pk)"

# 2. Current decryptable values in .env.secrets, if any. A secrets file we
#    cannot decrypt is unrecoverable from here — never overwrite it (dotenvx
#    set would reuse its public key and produce more values we can't read).
require_recoverable() { # require_recoverable <var> <decrypted value>
  grep -q "^$1=" "$SECRETS_FILE" || return 0
  [ -n "$2" ] && return 0
  warn "$SECRETS_FILE 에 $1 이(가) 있지만 복호화할 키를 찾지 못했습니다 (Keychain '$KEYCHAIN_SERVICE'·.env.keys 모두 없음)."
  echo "  키를 복구해 다시 실행하거나, 포기하려면 $SECRETS_FILE 을 직접 삭제 후 재실행하세요."
  exit 1
}

ENV_KEY_CUR=''
JWT_CUR=''
if [ -f "$SECRETS_FILE" ]; then
  ENV_KEY_CUR="$(decrypted ARCTURUS_ENV_KEY "$PK")"
  JWT_CUR="$(decrypted ARCTURUS_JWT_SECRET "$PK")"
  require_recoverable ARCTURUS_ENV_KEY "$ENV_KEY_CUR"
  require_recoverable ARCTURUS_JWT_SECRET "$JWT_CUR"
fi

# 3. Decide the values. Priority: already-encrypted value > legacy data file > fresh.
ENV_KEY_FILE="$DATA_DIR/env-key"
JWT_FILE="$DATA_DIR/jwt-secret"

resolve_value() { # resolve_value <current> <legacy file> <label>
  local cur="$1" file="$2" label="$3"
  if [ -n "$cur" ]; then
    say "$label: 기존 $SECRETS_FILE 값 유지" >&2
    printf '%s' "$cur"
  elif [ -f "$file" ]; then
    say "$label: 기존 $file 값을 이전 (기존 데이터/세션 유지)" >&2
    printf '%s' "$(cat "$file")"
  elif [ "$INPUT_MODE" = true ]; then
    # Prompt on /dev/tty so this works even though the function runs inside $(...)
    # (stdout is captured for the value). Blank → auto-generate.
    local entered
    read -rp "$label 값 입력 (빈칸=자동 생성 / Enter value, blank = auto-generate): " entered </dev/tty
    if [ -n "$entered" ]; then
      say "$label: 입력값 사용" >&2
      printf '%s' "$entered"
    else
      say "$label: 새로 생성" >&2
      openssl rand -hex 32
    fi
  else
    say "$label: 새로 생성" >&2
    openssl rand -hex 32
  fi
}

ENV_KEY_VAL="$(resolve_value "$ENV_KEY_CUR" "$ENV_KEY_FILE" "ARCTURUS_ENV_KEY")"
JWT_VAL="$(resolve_value "$JWT_CUR" "$JWT_FILE" "ARCTURUS_JWT_SECRET")"

# 4. Encrypt into .env.secrets (no-op for values already in place). A fresh
#    file gets a usage header first — dotenvx set preserves existing comments.
if [ ! -f "$SECRETS_FILE" ]; then
  cat > "$SECRETS_FILE" <<'EOF'
# 이 파일은 `bun run secrets:init`이 만들고 관리합니다.
# 시크릿 추가/수정: `KEY=평문` 한 줄 추가 → `bun run secrets:update` → `bun run server:restart`
# DOTENV_PUBLIC_KEY_SECRETS는 dotenvx가 자동 생성하는 암호화용 공개 키 — 직접 입력하지 마세요.
#
# Managed by `bun run secrets:init`. Add/change a secret: append `KEY=plainvalue`,
# then `bun run secrets:update` and `bun run server:restart`.
# DOTENV_PUBLIC_KEY_SECRETS is auto-generated by dotenvx — never set it yourself.
#
EOF
fi
[ "$ENV_KEY_CUR" = "$ENV_KEY_VAL" ] || bunx dotenvx set ARCTURUS_ENV_KEY "$ENV_KEY_VAL" -f "$SECRETS_FILE" >/dev/null
[ "$JWT_CUR" = "$JWT_VAL" ] || bunx dotenvx set ARCTURUS_JWT_SECRET "$JWT_VAL" -f "$SECRETS_FILE" >/dev/null
chmod 600 "$SECRETS_FILE"
ok "$SECRETS_FILE 암호화 저장 완료"

# 5. Make sure the private key is in the keychain (a fresh `dotenvx set` above
#    may have just created the keypair in .env.keys).
[ -n "$PK" ] || PK="$(keys_file_pk)"
if [ -z "$PK" ]; then
  warn "dotenvx private key를 찾지 못했습니다 — 아무것도 삭제하지 않았습니다."
  exit 1
fi
security add-generic-password -U -s "$KEYCHAIN_SERVICE" -a "$USER" -w "$PK"
ok "private key를 Keychain에 저장 (service: $KEYCHAIN_SERVICE)"

# 6. Verify a full round-trip strictly through the keychain before deleting anything.
KC_PK="$(security find-generic-password -s "$KEYCHAIN_SERVICE" -w)"
if [ "$(decrypted ARCTURUS_ENV_KEY "$KC_PK")" != "$ENV_KEY_VAL" ] ||
  [ "$(decrypted ARCTURUS_JWT_SECRET "$KC_PK")" != "$JWT_VAL" ]; then
  warn "Keychain 키 round-trip 검증 실패 — 아무것도 삭제하지 않았습니다."
  exit 1
fi
ok "Keychain 키로 복호화 round-trip 검증 통과"

# 7. Only now remove the plaintext copies.
if [ -f .env.keys ]; then
  rm .env.keys
  ok ".env.keys 삭제 — private key는 이제 Keychain에만 존재합니다"
fi
remove_legacy() { # remove_legacy <file> <expected value>
  [ -f "$1" ] || return 0
  if [ "$(cat "$1")" = "$2" ]; then
    rm "$1"
    ok "$1 삭제 (값은 $SECRETS_FILE 로 이전됨)"
  else
    warn "$1 의 값이 $SECRETS_FILE 과 달라 그대로 두었습니다 — 어느 키로 암호화된 데이터인지 확인 후 직접 정리하세요."
  fi
}
remove_legacy "$ENV_KEY_FILE" "$ENV_KEY_VAL"
remove_legacy "$JWT_FILE" "$JWT_VAL"

echo ""
ok "완료. 반영하려면:  bun run server:up   (dev는 bun run dev 그대로)"
echo "  · 시크릿 추가/수정:  $SECRETS_FILE 에 KEY=값 을 적고  bun run secrets:update"
echo "  · 다른 머신으로 이전 시 키 백업:  security find-generic-password -s $KEYCHAIN_SERVICE -w"
